# Generated by Django 4.0.2 on 2022-05-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.FloatField(blank=True, max_length=11, null=True)),
                ('balance', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('city_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.city')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
                ('route_category', models.CharField(max_length=50)),
                ('place_on_the_route', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_for_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.FloatField(max_length=10)),
                ('route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(max_length=10)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.client')),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.location')),
                ('route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.route')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_category', models.FloatField(max_length=10)),
                ('hotel_room', models.CharField(max_length=20)),
                ('room_price', models.FloatField(max_length=50)),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.location')),
                ('route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.route')),
            ],
        ),
    ]
